name: Node.js CI

on:
  pull_request

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 16.13.2
      uses: actions/setup-node@v3
      with:
        node-version: 16.13.2
        cache: 'yarn'
    - name: Install dependencies
      run: yarn

  lint:
    needs: install
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 16.13.2
      uses: actions/setup-node@v3
      with:
        node-version: 16.13.2
        cache: 'yarn'
    - name: Install dependencies
      run: yarn
    - name: Run eslint
      run: yarn lint

  build:
    needs: install
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 16.13.2
      uses: actions/setup-node@v3
      with:
        node-version: 16.13.2
        cache: 'yarn'
    - name: Install dependencies
      run: yarn
    - name: Run build
      run: yarn build